# Generated by Django 4.2.1 on 2023-06-02 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AeroCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yearOfCreation', models.IntegerField()),
                ('fliesOutOfEurope', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('manufacturerName', models.CharField(max_length=50)),
                ('maxNumberOfPassenger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('totalFlightHours', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PilotsInAeroCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerocompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaloniApp.aerocompany')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaloniApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Fligth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('airportNameDepart', models.CharField(max_length=50)),
                ('airportNameArrive', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/')),
                ('aeroCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaloniApp.aerocompany')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaloniApp.ballon')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaloniApp.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
