# Generated by Django 4.2.1 on 2023-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaloniApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fligth',
            name='image',
            field=models.ImageField(upload_to='testimages/'),
        ),
    ]
