# Generated by Django 4.2.1 on 2023-06-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRepairsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='manufacturers',
        ),
        migrations.CreateModel(
            name='ManufacturerWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoRepairsApp.manufacturer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoRepairsApp.workshop')),
            ],
        ),
    ]
