# Generated by Django 4.2.1 on 2023-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRepairsApp', '0003_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='link',
            field=models.URLField(),
        ),
    ]
